#!/bin/sh
if [ -f "/var/jb/usr/bin/launchctl" ]; then
    chown root:wheel /var/jb/Library/LaunchDaemons/c.eolnmsuk.corelliumdecoy.plist
    chmod 644 /var/jb/Library/LaunchDaemons/c.eolnmsuk.corelliumdecoy.plist
    /var/jb/usr/bin/launchctl load /var/jb/Library/LaunchDaemons/c.eolnmsuk.corelliumdecoy.plist
else
    chown root:wheel /Library/LaunchDaemons/c.eolnmsuk.corelliumdecoy.plist
    chmod 644 /Library/LaunchDaemons/c.eolnmsuk.corelliumdecoy.plist
    launchctl load /Library/LaunchDaemons/c.eolnmsuk.corelliumdecoy.plist
fi
exit 0
