#!/bin/sh
PREFIX=""
if [ -d /var/jb ]; then
    PREFIX="/var/jb"
fi

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    $PREFIX/usr/bin/launchctl unload $PREFIX/Library/LaunchDaemons/c.eolnmsuk.corelliumdecoy.plist 2>/dev/null || true
fi
exit 0
